Repository districtr/districtr-v2, pull requests merged in 2024-11, with the labels that each got.

#161 Fix backend tests
  .github/workflows/fly-deploy-pr.yml
  backend/app/alembic/versions/ccb2a6b81a8b_shattering.py
  backend/app/alembic/versions/dc391733e10a_add_extent_to_gerrydb.py
  backend/app/models.py
  backend/app/sql/create_districtr_map_udf.sql
  backend/app/utils.py
  backend/cli.py
  backend/tests/conftest.py
  backend/tests/test_utils.py
Labels: bug, database

#166 Implement county paint using FIPS prefix
  app/package-lock.json
  app/package.json
  app/src/app/utils/helpers.ts
Labels: bug, frontend

#165 Refactor tests to be idempotent
  backend/tests/conftest.py
  backend/tests/test_main.py
  backend/tests/test_utils.py
Labels: enhancement, CI/CD, database, devex

#173 Highlight unassigned geographies
  app/src/app/components/sidebar/Layers.tsx
  app/src/app/constants/layers.ts
  app/src/app/store/mapRenderSubs.ts
  app/src/app/store/mapStore.ts
  app/src/app/store/types.ts
Labels: enhancement, frontend

#179 Highlight bugfix
  app/src/app/constants/layers.ts
Labels: bug, frontend

#180 Bugfix - remove source
  app/src/app/constants/layers.ts
  app/src/app/store/mapStore.ts
Labels: bug, frontend

#189 Add CLI command and utility function to update a DistrictrMap
  backend/app/models.py
  backend/app/utils.py
  backend/cli.py
  backend/tests/test_utils.py
Labels: enhancement, CLI, devex

#190 Two or more races pop
  app/src/app/components/sidebar/Evaluation.tsx
  app/src/app/utils/api/apiHandlers.ts
  backend/app/alembic/versions/d90c9a1a246b_missing_two_or_more_races.py
  backend/app/main.py
  backend/app/models.py
  backend/app/sql/available_summary_stat_udf.sql
  backend/app/sql/summary_stats_p1.sql
  backend/app/sql/summary_stats_p1_totals.sql
  backend/app/sql/summary_stats_p4.sql
  backend/app/sql/summary_stats_p4_totals.sql
  backend/tests/fixtures/ks_demo_view_census_blocks_summary_stats.geojson
  backend/tests/fixtures/ks_demo_view_census_blocks_summary_stats_p4.geojson
  backend/tests/test_main.py
Labels: bug, API, frontend, database

#175 Update line layer widths
  app/src/app/constants/basemapLayers.ts
  app/src/app/constants/layers.ts
Labels: frontend

#185 Various bug fixes
  app/package-lock.json
  app/package.json
  app/src/app/components/ErrorNotification.tsx
  app/src/app/components/sidebar/ColorPicker.tsx
  app/src/app/map/page.tsx
  app/src/app/store/mapRenderSubs.ts
  app/src/app/store/mapStore.ts
  app/src/app/utils/api/queries.ts
  app/src/app/utils/events/mapEvents.ts
Labels: bug

#199 Paint by county with ID instead of features
  app/src/app/components/Map.tsx
  app/src/app/components/sidebar/PaintByCounty.tsx
  app/src/app/constants/layers.ts
  app/src/app/store/idCache.ts
  app/src/app/store/mapRenderSubs.ts
  app/src/app/store/mapStore.ts
  app/src/app/store/types.ts
  app/src/app/utils/events/mapEvents.ts
  app/src/app/utils/helpers.ts
Labels: bug, frontend
