Repository districtr/districtr-v2, pull requests merged in 2024-08, with the labels that each got.

#24 Feat/map controls
  app/package-lock.json
  app/package.json
  app/src/app/components/Map.tsx
  app/src/app/components/Sidebar.tsx
  app/src/app/components/sidebar/ColorPicker.jsx
  app/src/app/components/sidebar/MapModeSelector.jsx
  app/src/app/components/sidebar/Picker.jsx
  app/src/app/components/sidebar/ResetMapButton.tsx
  app/src/app/components/sidebar/Sidebar.tsx
  app/src/app/constants/colors.ts
  app/src/app/constants/layers.ts
  app/src/app/page.tsx
  app/src/app/store/mapStore.ts
  app/src/app/utils/events/handlers.ts
  app/src/app/utils/events/mapEvents.ts
  app/tsconfig.json
Labels: frontend

#20 Basic map selection
  app/.env.dev
  app/package-lock.json
  app/package.json
  app/src/app/api/apiHandlers.ts
  app/src/app/components/Map.tsx
  app/src/app/components/sidebar/GerryDBViewSelector.tsx
  app/src/app/components/sidebar/Sidebar.tsx
  app/src/app/constants/layers.ts
  app/src/app/constants/sources.ts
  app/src/app/page.tsx
  app/src/app/store/mapStore.ts
  app/src/app/utils/events/handlers.ts
  app/src/app/utils/events/mapEvents.ts
  backend/.dockerignore
  backend/app/alembic/env.py
  backend/app/alembic/versions/f09d9e802538_tiles_path.py
  backend/app/main.py
  backend/app/models.py
  backend/cli.py
  backend/scripts/load_gerrydb_view.sh
  backend/scripts/print_gerrydb_layer_info.sh
  backend/tests/test_main.py
Labels: enhancement, frontend, backend, cli, roadmap

#35 Midpoint feature additions
  app/package-lock.json
  app/package.json
  app/src/app/api/apiHandlers.ts
  app/src/app/components/Map.tsx
  app/src/app/components/navigation-events.ts
  app/src/app/components/sidebar/ColorPicker.jsx
  app/src/app/components/sidebar/GerryDBViewSelector.tsx
  app/src/app/components/sidebar/MapModeSelector.jsx
  app/src/app/components/sidebar/ResetMapButton.tsx
  app/src/app/components/sidebar/Sidebar.tsx
  app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
  app/src/app/constants/layers.ts
  app/src/app/constants/sources.ts
  app/src/app/store/mapStore.ts
  app/src/app/utils/events/handlers.ts
  app/src/app/utils/events/mapEvents.ts
  app/src/app/utils/helpers.ts
  backend/app/main.py
  backend/tests/test_main.py
Labels: bug, enhancement

#55 Districtr favicon
  app/src/app/favicon.ico
Labels: enhancement, frontend

#51 Configure sentry for FE
  .github/workflows/fly-deploy-api.yml
  .github/workflows/fly-deploy-app.yml
  app/.gitignore
  app/Dockerfile
  app/next.config.mjs
  app/package-lock.json
  app/package.json
  app/sentry.client.config.ts
  app/sentry.edge.config.ts
  app/sentry.server.config.ts
  app/src/app/api/sentry-example-api/route.ts
  app/src/app/global-error.tsx
  app/src/app/sentry-example-page/page.tsx
  app/src/instrumentation.ts
Labels: frontend, CI/CD

#60 Fix Fly FE Deploy
  .github/workflows/fly-deploy-api.yml
  .github/workflows/fly-deploy-app.yml
Labels: bug, frontend, CI/CD

#71 Update basemap and layers
  app/src/app/constants/basemapLayers.json
  app/src/app/constants/configuration.ts
  app/src/app/constants/layers.ts
  pipelines/simple_elt/__init__.py
  pipelines/simple_elt/files.py
  pipelines/simple_elt/main.py
  pipelines/simple_elt/requirements.txt
  pipelines/simple_elt/settings.py
Labels: enhancement, frontend, roadmap, layers

#72 County labels and painted layers toggle
  app/src/app/components/Map.tsx
  app/src/app/components/sidebar/GerryDBViewSelector.tsx
  app/src/app/components/sidebar/Layers.tsx
  app/src/app/components/sidebar/PaintByCounty.tsx
  app/src/app/components/sidebar/Sidebar.tsx
  app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
  app/src/app/constants/basemapLayers.ts
  app/src/app/constants/configuration.ts
  app/src/app/constants/layers.ts
  app/src/app/store/mapStore.ts
  app/src/app/utils/helpers.ts
Labels: enhancement, frontend, roadmap, layers

#73 Fix build: handle null map metrics again
  app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Labels: bug, frontend
