Repository districtr/districtr-v2, pull requests merged in 2024-09, with the labels that each got.

#75 Fix/map ux interactions
  app/package-lock.json
  app/package.json
  app/src/app/components/sidebar/BrushSizeSelector.tsx
  app/src/app/components/sidebar/Sidebar.tsx
  app/src/app/constants/layers.ts
  app/src/app/utils/events/mapEvents.ts
  app/tsconfig.json
Labels: bug, enhancement, frontend

#78 Recharts fix
  app/src/app/components/Map.tsx
  app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
Labels: enhancement, frontend

#85 Adjust brush size selector style
  app/src/app/components/sidebar/BrushSizeSelector.tsx
Labels: enhancement, frontend

#88 Docker compose config and data load script
  .gitignore
  README.md
  app/.env.docker
  app/Dockerfile.dev
  backend/.env.docker
  backend/Dockerfile.dev
  backend/scripts/load_data.py
  docker-compose.yml
Labels: devex
