Repository districtr/districtr-v2, pull requests merged in 2024-12, with the labels that each got.

#170 Add serialization to dev tools
  app/src/app/store/mapStore.ts
  app/src/app/store/middlewareConfig.ts
  app/src/app/store/persistConfig.ts
Labels: devex

#217 Population chart enhancements
  app/package-lock.json
  app/package.json
  app/src/app/components/InfoTip/InfoTip.tsx
  app/src/app/components/InfoTip/content.ts
  app/src/app/components/InfoTip/index.tsx
  app/src/app/components/Map.tsx
  app/src/app/components/MapTooltip.tsx
  app/src/app/components/sidebar/ColorPicker.tsx
  app/src/app/components/sidebar/DataPanels.tsx
  app/src/app/components/sidebar/Evaluation.tsx
  app/src/app/components/sidebar/Layers.tsx
  app/src/app/components/sidebar/PaintByCounty.tsx
  app/src/app/components/sidebar/Picker.jsx
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/LockIcon.tsx
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationChart.tsx
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationLabels.tsx
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationTooltip.tsx
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/types.ts
  app/src/app/components/sidebar/PopulationPanel/PopulationPanel.tsx
  app/src/app/components/sidebar/PopulationPanel/PopulationPanelOptions.tsx
  app/src/app/components/sidebar/PopulationPanel/index.tsx
  app/src/app/components/sidebar/ZonePicker.tsx
  app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
  app/src/app/store/chartStore.ts
  app/src/app/store/mapRenderSubs.ts
  app/src/app/store/mapStore.ts
  app/src/app/store/middlewareConfig.ts
  app/src/app/store/tooltipStore.ts
  app/src/app/store/types.ts
  app/src/app/utils/api/mutations.ts
  app/src/app/utils/api/queries.ts
  app/src/app/utils/events/mapEvents.ts
  app/src/app/utils/helpers.ts
  app/src/app/utils/numbers.ts
  app/src/app/utils/zone-helpers.ts
Labels: enhancement, frontend

#218 Fix pinch speed
  app/src/app/components/Map.tsx
  app/src/app/store/mapRenderSubs.ts
  app/src/app/utils/events/mapEvents.ts
Labels: bug, frontend

#222 Paint fixes
  app/src/app/components/sidebar/PopulationPanel/PopulationChart/PopulationChart.tsx
  app/src/app/store/idCache.ts
  app/src/app/utils/events/mapEvents.ts
  app/src/app/utils/helpers.ts
Labels: bug, frontend

#231 Update PR DB machine memory
  .github/workflows/fly-deploy-pr.yml
Labels: CI/CD, database

#232 Better FE request management
  app/src/app/store/mapEditSubs.ts
  app/src/app/store/mapStore.ts
  app/src/app/utils/api/apiHandlers.ts
  app/src/app/utils/api/mutations.ts
  app/src/app/utils/api/queries.ts
Labels: bug, frontend, database, high priority
